title: YOUR DATASET NAME
description: "One-sentence intro for your dataset."
url: https://a-yayaya.github.io   # 你的用户主页域名
baseurl: ""                       # 用户主页必须为空
lang: en

theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope: { path: "" }
    values:
      image: /assets/teaser.jpg   # 分享卡片图
